export const en = {
  search: "Search...",
  title: "Reddit Photo Gallery",
  searchPrompt: "Search for your favorite subreddit images!",
  back: "Back",
  author: "Author",
  subreddit: "Subreddit",
  ups: "Ups",
  description: "Description",
  noDescription: "No description available.",
  id: "ID",
  go_to_detail: "Go to details",
  notFoundTitle: "404 - Page Not Found",
  notFoundMessage: "Sorry, the page you are looking for does not exist.",
  goBackHome: "Go back to Home",
};
