export const tr = {
  search: "Ara...",
  title: "Reddit Fotoğraf Galerisi",
  searchPrompt: "Favori subreddit görsellerinizi arayın!",
  back: "Geri",
  author: "Yazar",
  subreddit: "Subreddit",
  ups: "Beğeni",
  description: "Açıklama",
  noDescription: "Açıklama mevcut değil.",
  id: "ID",
  go_to_detail: "Detaylara git",
  notFoundTitle: "404 - Sayfa Bulunamadı",
  notFoundMessage: "Üzgünüz, aradığınız sayfa mevcut değil.",
  goBackHome: "Ana sayfaya dön",
};
